# Generated by Django 4.1.7 on 2023-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="date_payed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
