# Generated by Django 4.1.7 on 2023-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_record_date_payed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="date_payed",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
