# Generated by Django 4.1.7 on 2023-06-06 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_record_date_payed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="date_payed",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2023, 6, 6, 16, 45, 0, 626179, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
