# Generated by Django 4.1.7 on 2023-06-06 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_record_date_payed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="date_payed",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
