# Generated by Django 4.1.7 on 2023-06-06 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_record_date_payed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="date_payed",
            field=models.DateField(
                blank=True, default=datetime.date(2023, 6, 6), null=True
            ),
        ),
    ]
